### ISSUE TITLE
Ready or Not | desktop game

### ISSUE THREAD

**Issue by Skellthing** [manucabral/RichPresencePlus#2]
### Software description

A Discord RPC for Ready or Not. (Including Mission and solo or multiplayer)

### Software name

Ready or Not

### Software URL

https://store.steampowered.com/app/1144200/Ready_or_Not/

### Paid service

- [ ] Yes
- [X] No

### Regional restrictions

- [ ] Yes
- [X] No

### Game

- [X] Yes
- [ ] No

**Comment by manucabral** [comment]
The rich presence was implemented to retrieve and display the current mission being played. However, the maximum information retrieved so far is only the mission name. You can take a look at the [examples here](https://github.com/manucabral/RichPresencePlus/tree/main/presences/Ready%20Or%20Not).

Remember to update to the new Steam-compatible version. [Rich Presence Plus v0.0.7-stable](https://github.com/manucabral/RichPresencePlus/releases/tag/v0.0.7-stable)
If you encounter any bugs or issues, please feel free to open a report.
