### ISSUE TITLE
Youtube Music | Presence Doesn't Update after Song Ends

### ISSUE THREAD

**Issue by aptravis-msft** [manucabral/RichPresencePlus#21]
### Steps to reproduce

1. Open the browser using the Rich Presence Plus App
2. Enable the Youtube Music Presence
3. Listen to a song on music.youtube.com
4. Verify that song appears in Discord
5. After song ends, check again and the song never updates

Stopping and reloading the presence does not update the song, and it's then stuck on "Initializing"
![image](https://github.com/user-attachments/assets/133a0c4a-7db9-4ed6-9b7f-0f1ccd78ece1)

### Expected behavior

Songs should update after ending 

### App version

v0.0.9

### Default Browser

Opera GX LVL 6 (core: 114.0.5282.148)

### Operating System

Windows 11 Pro 23H2 Build 22631.4317

### App log

[rpp.log](https://github.com/user-attachments/files/17684799/rpp.log)

**Comment by aptravis-msft** [comment]
I completely closed the browser and RPP applications and reopened them and attempted again. Discord never gets past initializing, but the YoutubeMusic log file at least sees the first song I open, though it never updates when the song changes, nor updates the presence in Discord.

I've attached the most recent YoutubeMusic log file as well. 
[YoutubeMusic.log](https://github.com/user-attachments/files/17684890/YoutubeMusic.log)

**Comment by aptravis-msft** [comment]
I narrows down the issue. The application behaves as expected(sort of) as long as YoutubeMusic is the ONLY tab open in the browser. As soon as another tab is opened, once the existing song ends it will never update again without completely closing both the browser and RPP.

The sort of, above is that the song title changes, but the length of the song is wrong. It just keeps appending more time to the length of the song. 

For example, I listened to a song in it's entirety. The song title updated, as expected, but instead of starting the timer at 0, it just kept going.

![image](https://github.com/user-attachments/assets/22c8ed63-877c-47de-b117-95b5f219b4ff)

**Comment by manucabral** [comment]
Hello, thank you for reporting this. What strikes me as odd is that the presence only works if it is the only **active tab** in the browser. Has this always happened to you?

I will escalate the bug so that it can be fixed as quickly as possible, as there are only two developers working on the application. If you need more information or have more details to share, you are welcome to join the Discord server or simply let me know in this issue. 

Regards.

**Comment by manucabral** [comment]
Fixed in the new app version [Rich Presence Plus v0.1.0](https://github.com/manucabral/RichPresencePlus/releases/tag/v0.1.0).
If any related issue arises, consider reopening this issue.
