### ISSUE TITLE
Application | YouTube & YouTube Music Intregrations disapeared from dashboard on Rich Presence Plus App

### ISSUE THREAD

**Issue by ShayTayUnknown** [manucabral/RichPresencePlus#23]
### Steps to reproduce

1. Deleted & Reinstalled Intregrations & deleted the TXt files as well for it.

2. Got in & out of the application Multi Times

### Expected behavior

Currently all I expect is to know how to fix this issue. Currently I ultimately resulted to deleting the WHOLE FOLDER and reinstalling it. So, if this happens again, I would like to know how to fix the problem, so I don't have to do that again.

### App version

v0.1.0

### Default Browser

Microsoft Edge 131.0.2903.70 

### Operating System

Windows 11 Pro 23H2

### App log

[rpp.log](https://github.com/user-attachments/files/17929528/rpp.log)

**Comment by manucabral** [comment]
Hello, the solution is update to the new version  [Rich Presence Plus v0.1.0](https://github.com/manucabral/RichPresencePlus/releases/tag/v0.1.0), which was released yesterday. If you encounter any other issues, please let me know

**Comment by manucabral** [comment]
Hello, the latest version v0.1.0, was released officially yesterday. Please remove your current app folder and download the latest version. Try using it, and if the issue persists, let me know.

New version: https://github.com/manucabral/RichPresencePlus/releases/tag/v0.1.0
