### ISSUE TITLE
Application | RichPresencePlus not opening

### ISSUE THREAD

**Issue by Litefox-HD** [manucabral/RichPresencePlus#3]
When I open the executable file I get the Error from the Picture. (My system is in german)
![Bild_2024-10-21_171318423](https://github.com/user-attachments/assets/20a30e4c-c922-4481-a28b-79e9fc257b35)
I have Python version 3.13.0 installed

**Comment by manucabral** [comment]
Hi,
It's an issue related to obtaining the name of the default browser. Which default browser do you have assigned on your system?

**Comment by Litefox-HD** [comment]
> Hi, It's an issue related to obtaining the name of the default browser. Which default browser do you have assigned on your system?

I use Opera GX

**Comment by manucabral** [comment]
> I use Opera GX

Nice, please attach the application log file (rpp.log) so I can create the patch for the new version compatible with your browser.

**Comment by Litefox-HD** [comment]
[rpp.log](https://github.com/user-attachments/files/17464099/rpp.log)

**Comment by manucabral** [comment]
> [rpp.log](https://github.com/user-attachments/files/17464099/rpp.log)

Thank you very much for reporting the bug. Let me know if you're still unable to use the application.
New version [Rich Presence Plus v0.0.6-stable](https://github.com/manucabral/RichPresencePlus/releases/tag/v0.0.6-stable)

**Comment by Litefox-HD** [comment]
It works now, thanks
