### ISSUE TITLE
Application | crash after clicking open browser (OperaGX)

### ISSUE THREAD

**Issue by Litefox-HD** [manucabral/RichPresencePlus#8]
### Steps to reproduce

1. Open the RichPresencePlus application
2. press "Open browser"
3. Then the Program freezes and crashes after some time

### Expected behavior

Opens the browser, then connects to it

### App version

v0.0.8 stable

### Default Browser

Opera GX LVL 6 (core: 114.0.5282.139)

### Operating System

Windows 10 Pro 22H2

### Screenshots

https://github.com/user-attachments/assets/041a5131-fe2c-40c8-a806-95a62c870326

### App log

[rpp.log](https://github.com/user-attachments/files/17586099/rpp.log)

**Comment by manucabral** [comment]
Hello, please try downloading the new executables of version 0.0.8 from the releases page. If it doesn't work, let me know.
